### PR TITLE
[its-vert] Small fixes to debug mode

### PR DESCRIPTION
**Pull request by mconcas**

### CODE REVIEW

**Comment by mconcas** [comment]
@davidrohr btw: 

```bash
input_line_46:1:10: fatal error: 'O2ITStrackingCUDA' file not found
#include "O2ITStrackingCUDA"
```

**Comment by davidrohr** [comment]
@mconcas : Can you be more specific, where do you see this error message?

**Comment by mconcas** [comment]
> @mconcas : Can you be more specific, where do you see this error message?

ok, was checking if it was my fault.
Actually, on dev branch it is broken as well.
Same as last time i am just trying to compile and launch `macros/run_primary_vertexer_ITS.C`
Without running it it breaks as well just trying to compile it, if you want to test.

**Comment by mconcas** [comment]
Update: Before #2632 everything was working fine.

> @mconcas : Can you be more specific, where do you see this error message?

I also tried checking out back to #2621, which used to work.
Ok, nevermind, I'll investigate, sorry for bothering.

Probably I should have not updated CUDA, I guess.

**Comment by davidrohr** [comment]
I don't see how #2632 could break this.
Just building the newest O2 dev now, perhaps I can have a look later.

**Comment by mconcas** [comment]
> I don't see how #2632 could break this. Just building the newest O2 dev now, perhaps I can have a look later.

no indeed, I think is something else. It looks something more subtle.
```bash
[O2/latest-5c3f0513d7-o2] /data1/ruben/pbpbVtx $> root -l -b -q run_primary_vertexer_ITS.C++

Processing run_primary_vertexer_ITS.C++...
Info in <TUnixSystem::ACLiC>: creating shared library /data1/ruben/pbpbVtx/./run_primary_vertexer_ITS_C.so
input_line_46:1:10: fatal error: 'O2ITStrackingCUDA' file not found
#include "O2ITStrackingCUDA"
         ^~~~~~~~~~~~~~~~~~~
Warning in <TInterpreter::TCling::RegisterModule>: Problems declaring payload for module run_primary_vertexer_ITS_C_ACLiC_dict.
input_line_49:2:3: error: use of undeclared identifier 'run_primary_vertexer_ITS'
 (run_primary_vertexer_ITS())
  ^
Error in <HandleInterpreterException>: Error evaluating expression (run_primary_vertexer_ITS()).
Execution of your code was aborted.
```

**Comment by davidrohr** [comment]
Why is it trying to include without .h? That sounds incorrect.

**Comment by mconcas** [comment]
> Why is it trying to include without .h? That sounds incorrect.

that's the problem: ` R__LOAD_LIBRARY(O2ITStrackingCUDA)` I think does something wrong, all of a sudden.

**Comment by mconcas** [comment]
> > Why is it trying to include without .h? That sounds incorrect.
> 
> that's the problem: ` R__LOAD_LIBRARY(O2ITStrackingCUDA)` I think does something wrong, all of a sudden.

Ok, I think I sorted out the thing. I just updated CUDA lately and now check_language(CUDA) does not find it.
I am trying to fix this without downgrading cuda, unless you know already that we cannot work with cuda 10.2.

**Comment by mconcas** [comment]
Ok, eventually I decided to get back to CUDA 10.1 and everything is back working.
Don't really think I did something wrong in the update procedure, tho.

So, after freezing rocm to 2.7 I'm also freezing cuda to 10.1 at least until the end of my thesis... :/

Thanks for helping, anyways

**Comment by mconcas** [comment]
Hi, @shahor02 @davidrohr 

If these tests pass I am ready to merge

Cheers
