### ISSUE TITLE
Problem with "constexpr static uint32_t" on MAC 10.12.3, Clang 800.0.38  

### ISSUE THREAD

**Issue by MohammadAlTurany** [AliceO2Group/AliceO2#280]
The dev branch does not compile on MAC OS 10.12.3 with Clang 800.0.38. I get the following error:

> 
> Undefined symbols for architecture x86_64:
>   "AliceO2::DataFlow::SubframeBuilderDevice::mDuration", referenced from:
>       AliceO2::DataFlow::SubframeBuilderDevice::SubframeBuilderDevice() in SubframeBuilderDevice.cxx.o
>       AliceO2::DataFlow::SubframeBuilderDevice::InitTask() in SubframeBuilderDevice.cxx.o
>       AliceO2::DataFlow::SubframeBuilderDevice::BuildAndSendFrame(FairMQParts&) in SubframeBuilderDevice.cxx.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [lib/libDataFlow.dylib] Error 1
> make[1]: *** [Utilities/DataFlow/CMakeFiles/DataFlow.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by MohammadAlTurany** [comment]
Bogdan already reported this! I will close this issue!!
