### PR TITLE
Fixing code checker errors

### PR DESCRIPTION
**Pull request by matthiasrichter**
Some code checker warnings have been introduced in 6065822182f888769126ccd11e7f5dc1433900ce

```
========== List of errors found ==========
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:63: error: use nullptr [modernize-use-nullptr]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:69: error: use nullptr [modernize-use-nullptr]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx:109:75: error: use nullptr [modernize-use-nullptr]
```

### CODE REVIEW

**Comment by davidrohr** [comment]
I just encountered the same error.
This offending file was just recently added for TOF reconstruction.
Merging, since this also breaks other pull requests.
