### PR TITLE
Use arrow config files

### PR DESCRIPTION
**Pull request by ktf**
Should be compatible with both 0.14.2 and 0.15+.

### CODE REVIEW

**Comment by aphecetche** [comment]
@ktf in fact I'm confused : why move the details of the find arrow from the module to the O2Dependencies.cmake ? It makes the O2Dependencies less clean

**Comment by ktf** [comment]
The problem is that since arrow 0.16.0  gandiva is in a separate config which requires it's own find_package(gandiva). Such a config does "find_package(arrow) which results in a cyclic dependency, because our own Findarrow.cmake is preferred. I tried renaming it to FindO2arrow.cmake, but I couldn't find the incantation to have it picked up. Do you have any idea why:

```
find_package(O2arrow)
```

would fail if I renamed such a file?

**Comment by aphecetche** [comment]
@ktf well, I'm trying a local build with arrow 0.16.0 to test the FindXXX stuff (noticed that now the package is called **A**rrow and no longer arrow) but I get an issue in Root. 

```
In file included from /Users/laurent/alice/cmake/sw/SOURCES/ROOT/v6-20-02-alice3/v6-20-02-alice3/tree/dataframe/src/RArrowDS.cxx:44:
/Users/laurent/alice/cmake/sw/osx_x86-64/arrow/v0.16.0-1/include/arrow/stl.h:32:10: fatal error: 'arrow/compute/api.h' file not found
#include "arrow/compute/api.h"
```

**Comment by ktf** [comment]
@aphecetche you will also need alisw/alidist#2196 or simply to use 0.14.2.

**Comment by ktf** [comment]
@aphecetche did you manage to try it out? I would otherwise merge this and we can clean up later.

**Comment by aphecetche** [comment]
@ktf I thought I commented yesterday, but it might have been during the Github glitch in the afternoon and it probably did not went through. My comment was : 

----
well, don't really want to rebuild root and co too often, so I've setup a [tiny project](https://github.com/aphecetche/cmake-play/tree/arrow-0.14-and-0.16) to play with `find_package(arrow)` "in isolation". 

The [Findarrow.cmake](https://github.com/aphecetche/cmake-play/blob/arrow-0.14-and-0.16/cmake/Findarrow.cmake) from this project should work with both arrow versions. The key "trick" to avoid recursion seems to be the `CMAKE_FIND_PACKAGE_PREFER_CONFIG` variable.
----

**Comment by ktf** [comment]
Ok, but how would this matter in this specific case? The config is provided in both cases and we do need our module for the customizations? In principle it's our module that is misnamed (because it's not really finding arrow, merely applying customisations) but I could not manage to rename it.

**Comment by aphecetche** [comment]
in 0.14 there's only one config = arrowConfig.cmake while there are two for 0.16 (ArrowConfig.cmake and GandivaConfig.cmake). The issue as you mentioned early on is that we get into recursion for 0.16 because of the GandivaConfig trying to find arrow and stumbling upon our Findarrow.cmake module before the (A)rrowConfig. The CMAKE_FIND_PACKAGE_PREFER_CONFIG prevents that. 

And I would argue that our Findarrow.cmake finds arrow (and configure a few things for us), whatever it's name is (arrow or Arrow) ?  

Whatever, my main "objection" to this PR as it is here is to avoid injecting find details into the O2Depedencies.cmake and keep them in the relevant Findxxx modules.

**Comment by ktf** [comment]
CMAKE_FIND_PACKAGE_PREFER_CONFIG will find arrow config in the first place, and our own Findarrow.cmake code will not be picked up, no?

**Comment by aphecetche** [comment]
The CMAKE_FIND_PACKAGE_PREFER_CONFIG is used inside our Findarrow.cmake : https://github.com/aphecetche/cmake-play/blob/arrow-0.14-and-0.16/cmake/Findarrow.cmake

**Comment by aphecetche** [comment]
btw, just in case you don't know that option, there's a `--debug-find` that can be used with the cmake command to see a bit more how and what CMake is finding.

**Comment by ktf** [comment]
Thanks I did not know about --debug-find. I will try.

I would still prefer renaming as an option. Your solution frankly seems to be overcomplicated (no offense) to avoid renaming a file. It will also make things more understandable in the toplevel O2Dependencies because it will be clear that:

```
find_package(O2arrow)
```

comes from us.

**Comment by aphecetche** [comment]
we can do the renaming as well, so the FindO2arrow.cmake will be a tad simpler, yes (just removing the CMAKE_FIND_PACKAGE_PREFER_CONFIG thingy in https://github.com/aphecetche/cmake-play/blob/arrow-0.14-and-0.16/cmake/Findarrow.cmake)

**Comment by ktf** [comment]
I could not manage to get the `FindO2arrow.cmake` to work. If you can rename it and get it to work with the current arrow, I am happy to take it from there.

**Comment by aphecetche** [comment]
ok, will do.

**Comment by aphecetche** [comment]
@ktf I've tested successfully the changes in https://github.com/AliceO2Group/AliceO2/pull/3419 : 

- locally on my Mac with arrow 0.14.1 and AliceO2
- locally on my Mac and Ubuntu with arrow 0.14.1 and 0.16.0 and cmake-play (i.e. w/o AliceO2)
