### ISSUE TITLE
no template named 'variant' in namespace 'std'

### ISSUE THREAD

**Issue by preghenella** [AliceO2Group/AliceO2#1420]
Dear all,

I get this compilation error while building `dev` as of today

/Users/preghenella/alisoft/sw/SOURCES/O2/dev/0/Framework/Core/include/Framework/DataDescriptorMatcher.h:123:19: error: no template named 'variant' in namespace 'std'

possibly a mac-related issue?

preghenella@robymacpro:~/alisoft> g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Thanks for hints to fix.
Roberto

**Comment by preghenella** [comment]
@ktf @dberzano , in case you have a hint to fix this.
Thanks

**Comment by ktf** [comment]
did you update to the latest alidist? Since a few weeks we require C++17 to be available in O2.

**Comment by preghenella** [comment]
thanks @ktf ,
alidist update helped with `variant`.
But I still fail the compilation.

Thanks

/Users/preghenella/alisoft/sw/SOURCES/O2/dev/0/Framework/Core/src/DataSampling.cxx:145:17: error: no viable conversion from 'Optional<std::__1::basic_string<char> >' (aka 'boost::optional<std::__1::basic_string<char> >') to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
    std::string taskNamesString = configFile->get<std::string>("qc.config.DataSampling.tasksList");
                ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:767:5: note: candidate constructor not viable: no known conversion from 'Optional<std::__1::basic_string<char> >' (aka 'boost::optional<std::__1::basic_string<char> >') to 'const std::__1::basic_string<char> &' for 1st argument
    basic_string(const basic_string& __str);
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:772:5: note: candidate constructor not viable: no known conversion from 'Optional<std::__1::basic_string<char> >' (aka 'boost::optional<std::__1::basic_string<char> >') to 'std::__1::basic_string<char> &&' for 1st argument
    basic_string(basic_string&& __str)
    ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:782:31: note: candidate constructor not viable: no known conversion from 'Optional<std::__1::basic_string<char> >' (aka 'boost::optional<std::__1::basic_string<char> >') to 'const char *' for 1st argument
    _LIBCPP_INLINE_VISIBILITY basic_string(const _CharT* __s);
                              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/string:815:5: note: candidate constructor not viable: no known conversion from 'Optional<std::__1::basic_string<char> >' (aka 'boost::optional<std::__1::basic_string<char> >') to 'initializer_list<char>' for 1st argument
    basic_string(initializer_list<_CharT> __il);

**Comment by ktf** [comment]
I suspect this is the Configuration issue @awegrzyn was fixing yesterday. Can you check you do have his commit in alidist as well?

**Comment by sawenzel** [comment]
Did you update O2, too? O2 dev was broken yesterday. (You need to update **everything**).

**Comment by awegrzyn** [comment]
This was fixed yesterday evening, sorry for the inconvenience.

**Comment by preghenella** [comment]
I have `pull --rebase` this morning.
Will try again.

**Comment by preghenella** [comment]
preghenella@robymacpro:~/alisoft/O2> git pull --rebase origin dev
From https://github.com/AliceO2Group/AliceO2
 * branch                dev        -> FETCH_HEAD
Already up to date.
Current branch dev is up to date.

**Comment by flodamas** [comment]
@preghenella you can download the 10.14 (Mojave) via the start menu of the App Store.
I have the same issue than you to build O2 since yesterday morning. I am updating to 10.14 right now so I would be able to tell you if it helps

**Comment by ktf** [comment]
That was unexpected. Sorry about that. I can make the code work on 10.13 if there is actual need for it (i.e. if people do not want to upgrade to mojave for some reason).

**Comment by sawenzel** [comment]
@ktf: I think the policy is to support at least the last 2 versions of macOS. So yes, I think it is mandatory to do so. (Unless a simple xcode update would help)

**Comment by dberzano** [comment]
The policy is indeed to support the two last versions of macOS and to always update Xcode in any case.

@preghenella I suggest you update Xcode first to see if it helps; in case it does not, it's better if we have a fix for High Sierra ☹️

**Comment by awegrzyn** [comment]
All right, but it means we can't use C++17...

**Comment by awegrzyn** [comment]
...and revert all these changes made in all repos to be compatible with 10.13.

**Comment by Barthelemy** [comment]
Or we could have `#ifdef` ? to adopt std::xxx isntead of boost::xxx if c++17 is found (which it won't on 10.3).

**Comment by dberzano** [comment]
@sawenzel we're absolutely not turning back here. The supported platform is, [as clearly stated at a CB](https://indico.cern.ch/event/642232/#3-wp3-common-tools-and-softwar), CC7. Other operating systems are supported as development platforms.

The policy of supporting the two last macOS versions strictly applies for Run 2 code. The easiest we can do here is to lower the bar a bit for O2: the solution is as easy as upgrading to Mojave, which is possible for every Mac < 7 years old, so @preghenella please do that 😄

**Comment by dberzano** [comment]
@Barthelemy I am not sure the changes are as easy as fitting into a small `#ifdef`. Visitor logics for instance, to my understanding, are a bit different.

**Comment by ktf** [comment]
I think rewriting the code without the `std::visit` so that it works on all platforms should be trivial. I will shortly look into it. The problem is with `visit`, not with `variant`, so I am not sure moving to `boost::variant` will not change things. 

Please do not revert it in the main repository.

**Comment by sawenzel** [comment]
@dberzano : Sorry to hear that. In my opinion it is wrong to impose an operating system which is barely weeks old. In the past, updating macOS was always a pain and I already lost many paid programs that used to work on older version but fail to do so in newer versions. I would appreciate a less disruptive approach.

**Comment by dberzano** [comment]
@sawenzel I would agree if O2 was production software. The Run 2 support model is more loose exactly because of that. We don't want to be behind for when O2 will become production, and it won't take much longer, so: biting the C++17 bullet now makes sure that every wrinkle will have been ironed out by then.

@ktf if it's easy to rewrite the visitor logic in a compatible way, let's do it.

**Comment by preghenella** [comment]
@dberzano , I have updated to Mojave and now I everything is dark ;-)
Will post back in case of troubles building

**Comment by preghenella** [comment]
ps: I also had to update CMD-line-tools
```
preghenella@robymacpro:~/alisoft/alidist> xcode-select --install
xcode-select: note: install requested for command line developer tools
```
otherwise
```
preghenella@robymacpro:~/alisoft> aliBuild --defaults o2 build O2
ERROR: Impossible to find reference for alidist 
```
```
preghenella@robymacpro:~/alisoft> cd alidist/
preghenella@robymacpro:~/alisoft/alidist> git pull --rebase origin master
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

**Comment by preghenella** [comment]
still not enough
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
#include_next <string.h>
```
```
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
```
and more similar.
Opening `Xcode` will ask to install additional components. But it does not solve anything.

Browsing the web I found this conversation about ROOT
https://root-forum.cern.ch/t/root-stopped-working-after-macos-update-to-mojave/30845/2

**Comment by awegrzyn** [comment]
As mentioned at some point by Dario upgrading the system requires following the same instructions as configuration aliBuild for the first time. Please take a look in here: https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-macos.html

**Comment by ktf** [comment]
So, I am working on a solution and it should be available soon. 

One thing we should do is to set `CMAKE_MACOSX_DEPLOYMENT_TARGET=10.13` so that while we keep building only on 10.14, we also check compatibility with 10.13.

**Comment by preghenella** [comment]
sorry, I believe I have upgraded everything.
Still
```
[  2%] Building CXX object CCDB/CMakeFiles/CCDB.dir/G__CCDBDict.cxx.o
In file included from /Users/preghenella/alisoft/sw/BUILD/30cedbc10e96d836ddd2f76abd677fa5c454c320/O2/CCDB/G__CCDBDict.cxx:7:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
```

what am I missing?

**Comment by ktf** [comment]
Remove and reinstall the command line utils...

--
Ciao,
Giulio

**Comment by ihrivnac** [comment]
Hi,
I got also problems on Mac 10.13.4 on Wednesday when updating alidist; on my side it is the error in building msgpack:
In file included from /Users/ivana/work/projects/aliceO2_mt/sw/SOURCES/msgpack/v2.1.5/cpp-2.1.5/include/msgpack/adaptor/cpp17/optional.hpp:14:
/Users/ivana/work/projects/aliceO2_mt/sw/SOURCES/msgpack/v2.1.5/cpp-2.1.5/include/msgpack/v1/adaptor/cpp17/optional.hpp:19:10: fatal error: 'optional' file not found
#include <optional>
         ^~~~~~~~~~
1 error generated.
I googled that my current version of xcode supports only <experimental/optional>; the next version of xcode requires to upgrade the system to Mojave.
As we have in one week a deadline for developments for Geant4 release (which happens once in a year), it's really very inconvenient to upgrade the system now. 
I don't know how many Mac machines do we have for integration tests, but if it's just one and we want to support two Mac versions, it's not sufficient and you should ask for another machine. In case we have two, then we should keep testing of both supported versions, so that we avoid such surprises in future.

**Comment by preghenella** [comment]
I'm still stuck with building the full soft-suite after macOS upgrade (Mojave).
I believe I have done everything that was supposed to be done after upgrades.

ROOT does not build.
The last error I have in the log file is
```
/Users/preghenella/alisoft/sw/BUILD/50a04a32ca6d7cea4cfdb02968c00262147aab1c/ROOT/include/TMathBase.h:147:18: error: expected unqualified-id
   { return std::signbit(a);  }
```

I attach the full log.
Thanks for help.

[build.log](https://github.com/AliceO2Group/AliceO2/files/2496389/build.log)

**Comment by awegrzyn** [comment]
I had the same problem, could you just try installing XCode?

**Comment by aphecetche** [comment]
Got also those errors on a brand new macOS 10.14 VM with only command line tools (not XCode).

As far as I can tell according to root forum (e.g. https://root-forum.cern.ch/t/error-while-compiling-root-6-14-04-on-macos-10-14-mojave/30987)  Root 6.14/04 is not ok on Mojave (unless you're willing to install extra package indicated in the discussion of that link), but the next tag (when is the question) should be work out-of-the-box. And my understanding is that this will not require full blown XCode. Command Line Tools should be enough then.

**Comment by preghenella** [comment]
hi @awegrzyn ,
I have Xcode installed `Version 10.0 (10A255)`.
I'm not sure if I interpret correctly @aphecetche: do I have to give up for some time?

**Comment by sawenzel** [comment]
For the record, after the update to 10.14 and reinstallation of command line tools, I am getting stuck much earlier with the following error during build of rapidjson:

```
 [ 26%] Building CXX object example/CMakeFiles/tutorial.dir/tutorial/tutorial.cpp.o
DEBUG:O2:RapidJSON:0: error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
```

Any clue? I have latest XCode 10A255. Apple LLVM version 10.0.0 (clang-1000.11.45.2)

**Comment by ktf** [comment]
Ciao,

The actual problem is that XCode10 removed support for stdlibc++.

Looks like the problem is that we are lacking "-std=libc++" in the RapidJSON cmakelists.

Not sure why I do not have the issue, though.

--
Ciao,
Giulio

**Comment by awegrzyn** [comment]
I have PR pending that drops `boost::variant` in favour of `std::variant`: https://github.com/AliceO2Group/Monitoring/pull/75
It does not compile on 10.13. I don't have a problem of delaying it a bit, but I'd like to know when I could merge it?

**Comment by ktf** [comment]
Why not simply using `std::get_if`? It's marginally more verbose than std::visit, but it works everywhere.

```C++
std::variant<int, float> foo;

if (auto val1 = std::get_if<int>(&foo)) {
  doInt(*val1);
} else (auto val2 = std::get_if<float>(&foo) {
  doInt(*val1);
} else {
  throw std::runtime_error("No match");
}
```

**Comment by awegrzyn** [comment]
Okay, but what about `std::variant` itself? It has the same issue as `std::visit`.

**Comment by ktf** [comment]
Nope. What breaks things on MacOS is the fact that std::visit, get and a few other methods raise an  exception which was unknown to the previous ABI, hence the problem. 

My experience is that if you stick with `std::get_if`, which does not throw, you are fine.

**Comment by awegrzyn** [comment]
All right, I'll try that!

**Comment by sawenzel** [comment]
I guess this can be closed? @preghenella ?
