### PR TITLE
Preparation for Pythia8315

### PR DESCRIPTION
**Pull request by pzhristov**
Mask the isospin information in the PDG code.
Use nCollND() instead of the deprecated nCollNDTot().

### CODE REVIEW

**Comment by pzhristov** [comment]
@sawenzel I am not sure why the fullCI fails, the inconsistency between the number of expected and processed primary particles is not related to the changes in the PR.

**Comment by sawenzel** [comment]
@pzhristov : The fullCI passes with your mods. Now the question is what will happen when we go to Pythia8314, where the change will be applied again?

**Comment by pzhristov** [comment]
@sawenzel The problem is that we add some "nuclei" with isospin one in the code itself, and I did not see them when checking the external file. I can change the logic and mask only if the isospin is 9.

**Comment by pzhristov** [comment]
Since isospin 9 is used to indicate beam remnants, it cannot simply be masked. Additional changes will address this issue.

**Comment by pzhristov** [comment]
@sawenzel @jackal1-66 I confirm that these changes work well with Pythia8.315 and the beam remnants are treated correctly in Geant4 (no exceptions). It is possible that there was a bug in the status code introduced in 8.314 that was fixed later in 8.315, but I did not investigate further. The compilation error on aarch64 is in Monitoring and not related to this PR. If you agree, I will merge it and prepare a PR to bump Pythia8

**Review by sawenzel — APPROVED** [review]
