### PR TITLE
[WIP] DPL: simplify input record API

### PR DESCRIPTION
**Pull request by matthiasrichter**
Using `constexpr if` for type dependent code branches

TODO:
- [ ] implement zero-copy for vectors of messageable type
- [ ] extend test_`InputRecord` unit test

### CODE REVIEW

**Comment by matthiasrichter** [comment]
The two CI failures are unrelated
- macos CI does not build because of a problem in FairRoot cmake
```
  Unknown CMake command "CHECK_SYMBOL_EXISTS".
```
- o2 CI fails after complete installation and running all tests successfully with
```
[[ RELWITHDEBINFO == COVERAGE ]]
```
work is ongoing to fix this.

**Comment by ktf** [comment]
For the record. The actual failure is an issue in QualityControl, reported at the top:

```
[  4%] Built target QualityControlTypes
[  5%] Generating G__QualityControl.cxx, ../lib/G__QualityControl_rdict.pcm, ../lib/libQualityControl.rootmap
gmake[2]: *** [Framework/G__QualityControl.cxx] Error 1
gmake[1]: *** [Framework/CMakeFiles/QualityControl.dir/all] Error 2
gmake: *** [all] Error 2
++ export ROOTSYS=/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-18-00-1
```

@Barthelemy @knopers8 could you take a look?

**Comment by sawenzel** [comment]
For me this breaks compilation of O2-dev on my Mac.

**Comment by ktf** [comment]
Same here, actually.

**Comment by ktf** [comment]
```
/Users/ktf/work/active/sw/SOURCES/O2/1.0.0/0/Framework/Core/include/Framework/InputRecord.h:190:18: note: 'get<o2::framework::DataRef>' declared here
  decltype(auto) get(char const* binding) const
                 ^
/Users/ktf/work/active/sw/SOURCES/O2/1.0.0/0/Framework/Core/include/Framework/InputRecord.h:339:20: error: function 'get<o2::framework::DataRef>' with deduced return type cannot be used before it is defined
      auto&& ref = get<DataRef>(binding);
```

is the actual error.

**Comment by knopers8** [comment]
git bisect pointed me to "Simplifying InputRecord API" as the breaker of QC. Most likely it is because of the same error as the one on Mac.
