### ISSUE TITLE
Link problem with Utilities/DataFlow LOG(INFO) a uint32_t

### ISSUE THREAD

**Issue by bovulpes** [AliceO2Group/AliceO2#279]
Hello,

The linking breakes at Utilities/DataFlow/src/SubframeBuilderDevice.cxx because of the lines where a LOG(NFO) tries to printout "mDuration", which is defined in the header as "constexpr static uint32_t" and if I cast it with "static_cast<uint64_t>(mDuration)" then it passes and the build is ok.

cheers,

Bogdan.

**Comment by sawenzel** [comment]
Seems there is a problem with
`constexpr const uint32_t mDuration`; changing this to just `uint32_t mDuration` should fix this for the moment. Will take care of this.

**Comment by ktf** [comment]
Weird. I am testing on both linux (via CI) and on my mac (Sierra)  and I do not have this kind of issue. Sorry about that. Will do some more checks and add your suggested fix.

**Comment by mkrzewic** [comment]
Hi, a constexpr variable must be initialized immediately. Also, constexpr is implicitly const, so const there is superfluous and might trigger a compiler error.

**Comment by sawenzel** [comment]
@mkrzewic : Sorry there was a typo in my message. It means "static" and we did immediately init the variable ...

**Comment by ktf** [comment]
Indeed. The actual code is:

```
class ... {
private:
constexpr static uint32_t mOrbitsPerTimeframe = 1;
constexpr static uint32_t mOrbitDuration = 1000000000;
constexpr static uint32_t mDuration = mOrbitsPerTimeframe * mOrbitDuration;
};
```

which to my knowledge is actually valid.

**Comment by sawenzel** [comment]
Compiles on my MAC with 10.11.6
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0

**Comment by mkrzewic** [comment]
looks valid, gcc 6.2 has no problems with it.

**Comment by sawenzel** [comment]
@bovulpes : What is your setup?

**Comment by bovulpes** [comment]
openSUSE 13.2 (Harlequin) (x86_64)
clang version 3.5.0 (tags/RELEASE_350/final 216961)
Target: x86_64-suse-linux

**Comment by MohammadAlTurany** [comment]
Crashes on my MAC with  10.12.3
Apple LLVM version 8.0.0 (clang-800.0.38)

**Comment by matthiasrichter** [comment]
Can you post the actual error from the compiler log?

**Comment by bovulpes** [comment]
/home/bogdan/Software/AliceO2_mft/Utilities/DataFlow/src/SubframeBuilderDevice.cxx:79: undefined reference to `AliceO2::DataFlow::SubframeBuilderDevice::mDuration'
collect2: error: ld returned 1 exit status

**Comment by MohammadAlTurany** [comment]
Undefined symbols for architecture x86_64:
  "AliceO2::DataFlow::SubframeBuilderDevice::mDuration", referenced from:
      AliceO2::DataFlow::SubframeBuilderDevice::SubframeBuilderDevice() in SubframeBuilderDevice.cxx.o
      AliceO2::DataFlow::SubframeBuilderDevice::InitTask() in SubframeBuilderDevice.cxx.o
      AliceO2::DataFlow::SubframeBuilderDevice::BuildAndSendFrame(FairMQParts&) in SubframeBuilderDevice.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libDataFlow.dylib] Error 1

**Comment by sawenzel** [comment]
@MohammadAlTurany @bovulpes : Can you please check if my pull request #281 solves your issue?
( you might have to fetch branch swenzel/fix279 from my fork ).

**Comment by MohammadAlTurany** [comment]
@sawenzel It worked for me!

**Comment by bovulpes** [comment]
@sawenzel : works for me too. thanks!
